/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NationsRouteImport } from './routes/nations'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NationsCodeRouteImport } from './routes/nations.$code'
import { Route as AuthenticatedPassportRouteImport } from './routes/_authenticated/passport'
import { Route as AuthenticatedMatchdayRouteImport } from './routes/_authenticated/matchday'
import { Route as AuthenticatedCirclesRouteImport } from './routes/_authenticated/circles'

const NationsRoute = NationsRouteImport.update({
  id: '/nations',
  path: '/nations',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NationsCodeRoute = NationsCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => NationsRoute,
} as any)
const AuthenticatedPassportRoute = AuthenticatedPassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMatchdayRoute = AuthenticatedMatchdayRouteImport.update({
  id: '/matchday',
  path: '/matchday',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCirclesRoute = AuthenticatedCirclesRouteImport.update({
  id: '/circles',
  path: '/circles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/nations': typeof NationsRouteWithChildren
  '/circles': typeof AuthenticatedCirclesRoute
  '/matchday': typeof AuthenticatedMatchdayRoute
  '/passport': typeof AuthenticatedPassportRoute
  '/nations/$code': typeof NationsCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/nations': typeof NationsRouteWithChildren
  '/circles': typeof AuthenticatedCirclesRoute
  '/matchday': typeof AuthenticatedMatchdayRoute
  '/passport': typeof AuthenticatedPassportRoute
  '/nations/$code': typeof NationsCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/nations': typeof NationsRouteWithChildren
  '/_authenticated/circles': typeof AuthenticatedCirclesRoute
  '/_authenticated/matchday': typeof AuthenticatedMatchdayRoute
  '/_authenticated/passport': typeof AuthenticatedPassportRoute
  '/nations/$code': typeof NationsCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/nations'
    | '/circles'
    | '/matchday'
    | '/passport'
    | '/nations/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/nations'
    | '/circles'
    | '/matchday'
    | '/passport'
    | '/nations/$code'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/nations'
    | '/_authenticated/circles'
    | '/_authenticated/matchday'
    | '/_authenticated/passport'
    | '/nations/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  NationsRoute: typeof NationsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nations': {
      id: '/nations'
      path: '/nations'
      fullPath: '/nations'
      preLoaderRoute: typeof NationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nations/$code': {
      id: '/nations/$code'
      path: '/$code'
      fullPath: '/nations/$code'
      preLoaderRoute: typeof NationsCodeRouteImport
      parentRoute: typeof NationsRoute
    }
    '/_authenticated/passport': {
      id: '/_authenticated/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof AuthenticatedPassportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matchday': {
      id: '/_authenticated/matchday'
      path: '/matchday'
      fullPath: '/matchday'
      preLoaderRoute: typeof AuthenticatedMatchdayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/circles': {
      id: '/_authenticated/circles'
      path: '/circles'
      fullPath: '/circles'
      preLoaderRoute: typeof AuthenticatedCirclesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCirclesRoute: typeof AuthenticatedCirclesRoute
  AuthenticatedMatchdayRoute: typeof AuthenticatedMatchdayRoute
  AuthenticatedPassportRoute: typeof AuthenticatedPassportRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCirclesRoute: AuthenticatedCirclesRoute,
  AuthenticatedMatchdayRoute: AuthenticatedMatchdayRoute,
  AuthenticatedPassportRoute: AuthenticatedPassportRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface NationsRouteChildren {
  NationsCodeRoute: typeof NationsCodeRoute
}

const NationsRouteChildren: NationsRouteChildren = {
  NationsCodeRoute: NationsCodeRoute,
}

const NationsRouteWithChildren =
  NationsRoute._addFileChildren(NationsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  NationsRoute: NationsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
